spring.application.name=HospitalManagementCRUD

spring.datasource.url=jdbc:mysql://root:VqfjLJFSlwuNFevySoQgiTNppHMioerb@autorack.proxy.rlwy.net:26835/railway

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

spring.main.allow-bean-definition-overriding=true
